name: multi-nlp
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py310h699e580_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_4
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310h1637853_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pywin32=311=py310h282bd7d_1
  - pyzmq=27.1.0=py310h535538e_0
  - setuptools=80.9.0=py310haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py310h29418f3_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - altair==6.0.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.61.0
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - langdetect==1.0.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - narwhals==2.13.0
      - networkx==3.4.2
      - nltk==3.9.2
      - numpy==2.2.6
      - pandas==2.3.3
      - pillow==12.0.0
      - plotly==6.5.0
      - praw==7.8.1
      - prawcore==2.4.0
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - sentencepiece==0.2.1
      - smmap==5.0.2
      - streamlit==1.52.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - tzdata==2025.2
      - update-checker==0.18.0
      - urllib3==2.6.1
      - watchdog==6.0.0
      - websocket-client==1.9.0
      - wordcloud==1.9.4

